particlesJS("particles-js",
    {
        "particles":{
            "number":{
                "value":3,
                "density":{
                    "enable":true,
                    "value_area":789.1476416322727
                }
            },
            "color":{
                "value":"#ffffff"
            },
            "shape":{
                "type":"image",
                "stroke":{
                    "width":0,
                    "color":"#000000"
                },
                "polygon":{
                    "nb_sides":5
                },
                "image":{
                    "src":"images/2.png"
                }
            },
            "opacity":{
                "value":1,
                "random":true,
                "anim":{
                    "enable":true,
                    "speed":1,
                    "opacity_min":0,
                    "sync":false
                }
            },
            "size":{
                "value":40,
                "random":true,
                "anim":{
                    "enable":false,
                    "speed":36.54347455356053,
                    "size_min":0.5,
                    "sync":false
                }
            },
            "line_linked":{
                "enable":false,
                "distance":150,
                "color":"#ffffff",
                "opacity":0.4,
                "width":1
            },
            "move":{
                "enable":true,
                "speed":1,
                "direction":"none",
                "random":true,
                "straight":false,
                "out_mode":"out",
                "bounce":false,
                "attract":{
                    "enable":false,
                    "rotateX":600,
                    "rotateY":600
                }
            }
        },
    }
    );

particlesJS("particles-js2",
    {
        "particles":{
            "number":{
                "value":3,
                "density":{
                    "enable":true,
                    "value_area":789.1476416322727
                }
            },
            "color":{
                "value":"#ffffff"
            },
            "shape":{
                "type":"image",
                "stroke":{
                    "width":0,
                    "color":"#000000"
                },
                "polygon":{
                    "nb_sides":5
                },
                "image":{
                    "src":"images/8.png",
                    "height":100,
                    "width":193
                }
            },
            "opacity":{
                "value":1,
                "random":true,
                "anim":{
                    "enable":true,
                    "speed":1,
                    "opacity_min":0,
                    "sync":false
                }
            },
            "size":{
                "value":40,
                "random":true,
                "anim":{
                    "enable":false,
                    "speed":36.54347455356053,
                    "size_min":0.5,
                    "sync":false
                }
            },
            "line_linked":{
                "enable":false,
                "distance":150,
                "color":"#ffffff",
                "opacity":0.4,
                "width":1
            },
            "move":{
                "enable":true,
                "speed":1,
                "direction":"none",
                "random":true,
                "straight":false,
                "out_mode":"out",
                "bounce":false,
                "attract":{
                    "enable":false,
                    "rotateX":600,
                    "rotateY":600
                }
            }
        },
    }
);

particlesJS("particles-js3",
    {
        "particles":{
            "number":{
                "value":3,
                "density":{
                    "enable":true,
                    "value_area":789.1476416322727
                }
            },
            "color":{
                "value":"#ffffff"
            },
            "shape":{
                "type":"image",
                "stroke":{
                    "width":0,
                    "color":"#000000"
                },
                "polygon":{
                    "nb_sides":5
                },
                "image":{
                    "src":"images/6.png",
                    "width":204,
                    "height":100
                }
            },
            "opacity":{
                "value":1,
                "random":true,
                "anim":{
                    "enable":true,
                    "speed":1,
                    "opacity_min":0,
                    "sync":false
                }
            },
            "size":{
                "value":50,
                "random":true,
                "anim":{
                    "enable":false,
                    "speed":36.54347455356053,
                    "size_min":1,
                    "sync":false
                }
            },
            "move":{
                "enable":true,
                "speed":1,
                "direction":"none",
                "random":true,
                "straight":false,
                "out_mode":"out",
                "bounce":true
            }
        }
    }
);
